/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hesapmakinesi2;

import javax.swing.JOptionPane;

/**
 *
 * @author Çağan
 */
public class NewJFrame extends javax.swing.JFrame {
   double NumEnter1;
    double NumEnter2;
    double Result;
    String op;
    public NewJFrame(){
        initComponents();
    }
    /**
     * Creates new form NewJFrame
     */
    
   
    private void EnterNumbers(String q){
      String Nums = sonuc.getText() + q;
         sonuc.setText(Nums);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        beş = new javax.swing.JButton();
        artıeksi = new javax.swing.JButton();
        pokuz = new javax.swing.JButton();
        artı = new javax.swing.JButton();
        yüzde = new javax.swing.JButton();
        bolü = new javax.swing.JButton();
        sekiz = new javax.swing.JButton();
        üç = new javax.swing.JButton();
        AC = new javax.swing.JButton();
        iki = new javax.swing.JButton();
        eksi = new javax.swing.JButton();
        yedi = new javax.swing.JButton();
        dört = new javax.swing.JButton();
        bir = new javax.swing.JButton();
        nokta = new javax.swing.JButton();
        sıfır = new javax.swing.JButton();
        çarpı = new javax.swing.JButton();
        eşittir = new javax.swing.JButton();
        altı = new javax.swing.JButton();
        sonuc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        a.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("                     ÇAĞAN HESAPLAMA");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        beş.setBackground(new java.awt.Color(204, 204, 255));
        beş.setText("5");
        beş.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beşActionPerformed(evt);
            }
        });

        artıeksi.setBackground(new java.awt.Color(51, 255, 204));
        artıeksi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        artıeksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hesapmakinesi2/plus_minus_icon_174310.png"))); // NOI18N
        artıeksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artıeksiActionPerformed(evt);
            }
        });

        pokuz.setBackground(new java.awt.Color(204, 204, 255));
        pokuz.setText("9");
        pokuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokuzActionPerformed(evt);
            }
        });

        artı.setBackground(new java.awt.Color(255, 0, 153));
        artı.setText("+");
        artı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artıActionPerformed(evt);
            }
        });

        yüzde.setBackground(new java.awt.Color(51, 255, 204));
        yüzde.setText("%");
        yüzde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yüzdeActionPerformed(evt);
            }
        });

        bolü.setBackground(new java.awt.Color(255, 51, 153));
        bolü.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bolü.setText("÷");
        bolü.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolüActionPerformed(evt);
            }
        });

        sekiz.setBackground(new java.awt.Color(204, 204, 255));
        sekiz.setText("8");
        sekiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sekizActionPerformed(evt);
            }
        });

        üç.setBackground(new java.awt.Color(204, 204, 255));
        üç.setText("3");
        üç.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                üçActionPerformed(evt);
            }
        });

        AC.setBackground(new java.awt.Color(51, 255, 204));
        AC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AC.setText("AC");
        AC.setToolTipText("");
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });

        iki.setBackground(new java.awt.Color(204, 204, 255));
        iki.setText("2");
        iki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ikiActionPerformed(evt);
            }
        });

        eksi.setBackground(new java.awt.Color(255, 0, 153));
        eksi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        eksi.setText("-");
        eksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eksiActionPerformed(evt);
            }
        });

        yedi.setBackground(new java.awt.Color(204, 204, 255));
        yedi.setText("7");
        yedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yediActionPerformed(evt);
            }
        });

        dört.setBackground(new java.awt.Color(204, 204, 255));
        dört.setText("4");
        dört.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dörtActionPerformed(evt);
            }
        });

        bir.setBackground(new java.awt.Color(204, 204, 255));
        bir.setText("1");
        bir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birActionPerformed(evt);
            }
        });

        nokta.setBackground(new java.awt.Color(204, 204, 255));
        nokta.setText(".");
        nokta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noktaActionPerformed(evt);
            }
        });

        sıfır.setBackground(new java.awt.Color(204, 204, 255));
        sıfır.setText("0");
        sıfır.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sıfırActionPerformed(evt);
            }
        });

        çarpı.setBackground(new java.awt.Color(255, 0, 153));
        çarpı.setText("X");
        çarpı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                çarpıActionPerformed(evt);
            }
        });

        eşittir.setBackground(new java.awt.Color(255, 0, 153));
        eşittir.setText("=");
        eşittir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eşittirActionPerformed(evt);
            }
        });

        altı.setBackground(new java.awt.Color(204, 204, 255));
        altı.setText("6");
        altı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altıActionPerformed(evt);
            }
        });

        sonuc.setBackground(new java.awt.Color(0, 0, 0));
        sonuc.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        sonuc.setForeground(new java.awt.Color(255, 255, 255));
        sonuc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sonuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout aLayout = new javax.swing.GroupLayout(a);
        a.setLayout(aLayout);
        aLayout.setHorizontalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sonuc, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, aLayout.createSequentialGroup()
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(aLayout.createSequentialGroup()
                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AC, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(dört, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(yedi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(beş, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(artıeksi, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sıfır, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(aLayout.createSequentialGroup()
                                    .addComponent(bir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(iki, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yüzde, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(altı, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(üç, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nokta, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(çarpı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bolü, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eksi, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(artı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eşittir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(aLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        aLayout.setVerticalGroup(
            aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(yüzde, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bolü, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(artıeksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(çarpı, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beş, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dört, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altı, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iki, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artı, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(üç, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sıfır, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eşittir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nokta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(a, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void beşActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beşActionPerformed
      EnterNumbers("5"); // TODO add your handling code here:
    }//GEN-LAST:event_beşActionPerformed

    private void pokuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokuzActionPerformed
      EnterNumbers("9"); 
    }//GEN-LAST:event_pokuzActionPerformed

    private void ikiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ikiActionPerformed
       EnterNumbers("2");
       
    }//GEN-LAST:event_ikiActionPerformed

    private void yediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yediActionPerformed
       EnterNumbers("7");// TODO add your handling code here:
    }//GEN-LAST:event_yediActionPerformed

    private void noktaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noktaActionPerformed
       if (! sonuc.getText().contains("."))
       {
           sonuc.setText(sonuc.getText() + nokta.getText());
       }
   // TODO add your handling code here:
    }//GEN-LAST:event_noktaActionPerformed

    private void sonucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sonucActionPerformed

    private void birActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birActionPerformed
        EnterNumbers("1");       // TODO add your handling code here:
    }//GEN-LAST:event_birActionPerformed

    private void üçActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_üçActionPerformed
       EnterNumbers("3");// TODO add your handling code here:
    }//GEN-LAST:event_üçActionPerformed

    private void dörtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dörtActionPerformed
     EnterNumbers("4"); // TODO add your handling code here:
    }//GEN-LAST:event_dörtActionPerformed

    private void altıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altıActionPerformed
     EnterNumbers("6");  // TODO add your handling code here:
    }//GEN-LAST:event_altıActionPerformed

    private void sekizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sekizActionPerformed
        EnterNumbers("8");
    }//GEN-LAST:event_sekizActionPerformed

    private void sıfırActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sıfırActionPerformed
     EnterNumbers("0"); // TODO add your handling code here:
    }//GEN-LAST:event_sıfırActionPerformed

    private void çarpıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_çarpıActionPerformed
       NumEnter1 = Double.parseDouble(sonuc.getText());
       sonuc.setText("");
       op ="x";  // TODO add your handling code here:
    }//GEN-LAST:event_çarpıActionPerformed

    private void bolüActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolüActionPerformed
     NumEnter1 = Double.parseDouble(sonuc.getText());
       sonuc.setText("");
       op ="÷";   // TODO add your handling code here:
    }//GEN-LAST:event_bolüActionPerformed

    private void eksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eksiActionPerformed
    NumEnter1 = Double.parseDouble(sonuc.getText());
       sonuc.setText("");
       op ="-";    // TODO add your handling code here:
    }//GEN-LAST:event_eksiActionPerformed

    private void artıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artıActionPerformed
     NumEnter1 = Double.parseDouble(sonuc.getText());
      sonuc.setText("");
       op ="+";
    // TODO add your handling code here:
    }//GEN-LAST:event_artıActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
    sonuc.setText("");
       
       String Fn, Sn;
       Fn = String.valueOf(NumEnter1);
       Sn = String.valueOf(NumEnter2);
       
       Fn = ""; 
       Sn = "";
  // TODO add your handling code here:
    }//GEN-LAST:event_ACActionPerformed

    private void artıeksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artıeksiActionPerformed
      double nums = Double.parseDouble(String.valueOf(sonuc.getText()));
     nums = nums * (-1);
    sonuc.setText(String.valueOf(nums));
   // TODO add your handling code here:
    }//GEN-LAST:event_artıeksiActionPerformed

    private void eşittirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eşittirActionPerformed
     
 NumEnter2 = Double.parseDouble(sonuc.getText());
  if ( op == "+")
  {
      Result = NumEnter1 + NumEnter2;
     sonuc.setText(String.valueOf(Result));
  }
  else if (op == "-")
  {
      Result = NumEnter1 - NumEnter2;
     sonuc.setText(String.valueOf(Result));
  } 
  else if (op == "x")
  {
      Result = NumEnter1 * NumEnter2;
     sonuc.setText(String.valueOf(Result));
  }
   else if (op == "÷")
  {
      Result = NumEnter1 / NumEnter2;
     sonuc.setText(String.valueOf(Result));
  }
   // TODO add your handling code here:
    }//GEN-LAST:event_eşittirActionPerformed

    private void yüzdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yüzdeActionPerformed
       try {
        if (!sonuc.getText().isEmpty()) {
            double girilenSayi = Double.parseDouble(sonuc.getText());
            double yuzdeSonuc = girilenSayi / 100;

            sonuc.setText(String.valueOf(yuzdeSonuc));
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Geçerli sayısal bir yüzde değeri giriniz.", "Hata", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_yüzdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JPanel a;
    private javax.swing.JButton altı;
    private javax.swing.JButton artı;
    private javax.swing.JButton artıeksi;
    private javax.swing.JButton beş;
    private javax.swing.JButton bir;
    private javax.swing.JButton bolü;
    private javax.swing.JButton dört;
    private javax.swing.JButton eksi;
    private javax.swing.JButton eşittir;
    private javax.swing.JButton iki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nokta;
    private javax.swing.JButton pokuz;
    private javax.swing.JButton sekiz;
    private javax.swing.JTextField sonuc;
    private javax.swing.JButton sıfır;
    private javax.swing.JButton yedi;
    private javax.swing.JButton yüzde;
    private javax.swing.JButton çarpı;
    private javax.swing.JButton üç;
    // End of variables declaration//GEN-END:variables
}
